-- ============================================================
-- Seed deshabilitado (sin datos de ejemplo).
-- La BD arranca vacía; los datos llegan por importación desde
-- datos.bne.es o por la API.
-- ============================================================
